defmodule AutomatronEx.Repo.Migrations.CreateRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:runs, primary_key: false) do
      add :run_id, :text, null: false, primary_key: true
      add :trader_id, :text
      add :strategy, :text
      add :total_positions, :bigint, null: false, default: 0
      add :total_fills, :bigint, null: false, default: 0
      add :total_pnl, :float
      add :win_rate, :float
      add :expectancy, :float
      add :sharpe_ratio, :float
      add :avg_win, :float
      add :avg_loss, :float
      add :win_loss_ratio, :float
      add :wins, :bigint
      add :losses, :bigint
      add :avg_hold_hours, :float
      add :pnl_per_week, :float
      add :trades_per_week, :float

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:runs)
  end
end
